### ISSUE TITLE
panic happens

### ISSUE THREAD

**Issue by daviszhen** [matrixorigin/linter#11]
➜  mo-backup git:(0724-add-parameters) ✗ make static-check
[Create build config]
Neither 'fmt.Errorf()' nor 'errors.New()' is found
go vet -vettool=`which molint` github.com/matrixorigin/mo-backup/cmd/mo_br github.com/matrixorigin/mo-backup/pkg/backup github.com/matrixorigin/mo-backup/pkg/config github.com/matrixorigin/mo-backup/pkg/fs github.com/matrixorigin/mo-backup/pkg/run github.com/matrixorigin/mo-backup/pkg/version
# github.com/matrixorigin/mo-backup/pkg/run
panic: failed to identify method/function details

goroutine 9 [running]:
github.com/matrixorigin/linter/checklog.run.func1({0x1358f28?, 0xc000162740})
	/Users/pengzhen/go/src/github.com/matrixorigin/linter@v0.0.0-20230714054526-b7b474b07abb/checklog/checklog.go:89 +0x535
golang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0xc00049d7e8, {0xc000a1ab78?, 0x2?, 0x12e86e0?}, 0xc000badb60)
	/Users/pengzhen/go/src/golang.org/x/tools@v0.7.1-0.20230308011436-dd1e2f66b242/go/ast/inspector/inspector.go:81 +0x9f
github.com/matrixorigin/linter/checklog.run(0xc0009561e0)
	/Users/pengzhen/go/src/github.com/matrixorigin/linter@v0.0.0-20230714054526-b7b474b07abb/checklog/checklog.go:57 +0x137
golang.org/x/tools/go/analysis/unitchecker.run.func5.1()
	/Users/pengzhen/go/src/golang.org/x/tools@v0.7.1-0.20230308011436-dd1e2f66b242/go/analysis/unitchecker/unitchecker.go:359 +0x904
sync.(*Once).doSlow(0x12aab20?, 0xc0009085d0?)
	/usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:65
golang.org/x/tools/go/analysis/unitchecker.run.func5(0x14da5a0)
	/Users/pengzhen/go/src/golang.org/x/tools@v0.7.1-0.20230308011436-dd1e2f66b242/go/analysis/unitchecker/unitchecker.go:310 +0x1a5
golang.org/x/tools/go/analysis/unitchecker.run.func6.1(0x0?)
	/Users/pengzhen/go/src/golang.org/x/tools@v0.7.1-0.20230308011436-dd1e2f66b242/go/analysis/unitchecker/unitchecker.go:371 +0x29
created by golang.org/x/tools/go/analysis/unitchecker.run.func6
	/Users/pengzhen/go/src/golang.org/x/tools@v0.7.1-0.20230308011436-dd1e2f66b242/go/analysis/unitchecker/unitchecker.go:370 +0x47
make: *** [static-check] Error 1

**Comment by xzxiong** [comment]
repro in https://github.com/matrixorigin/matrixone/actions/runs/11626869179/job/32379327084?pr=19718

```
[Create build config]
make[1]: Entering directory '/home/runner/work/matrixone/matrixone/cgo'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/runner/work/matrixone/matrixone/cgo'
Does not find 'fmt.Errorf()', 'errors.New()','context.WithTimeout' and 'context.WithDeadline'
CGO_CFLAGS="-I/home/runner/work/matrixone/matrixone/cgo " CGO_LDFLAGS="-L/home/runner/work/matrixone/matrixone/cgo -lm -lmo" go vet -vettool=`which molint` ./...
# github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/merge/simulation
# [github.com/matrixorigin/matrixone/pkg/vm/engine/tae/db/merge/simulation]
panic: failed to identify method/function details

goroutine 35 [running]:
github.com/matrixorigin/linter/checklog.run.func1({0x7a5fe0, 0xc00010f480})
	../../../go/pkg/mod/github.com/matrixorigin/linter@v0.0.0-20241101034905-3[6](https://github.com/matrixorigin/matrixone/actions/runs/11626869179/job/32379327084?pr=19718#step:6:7)c04639c58c/checklog/checklog.go:90 +0x552
golang.org/x/tools/go/ast/inspector.(*Inspector).Preorder(0xc000a1e168, {0xc000a26cb8?, 0x95e180?, 0x10?}, 0xc000b1[7](https://github.com/matrixorigin/matrixone/actions/runs/11626869179/job/32379327084?pr=19718#step:6:8)b58)
	../../../go/pkg/mod/golang.org/x/tools@v0.7.1-0.2023030[8](https://github.com/matrixorigin/matrixone/actions/runs/11626869179/job/32379327084?pr=19718#step:6:9)011436-dd1e2f66b242/go/ast/inspector/inspector.go:81 +0x8f
github.com/matrixorigin/linter/checklog.run(0xc000a2a0f0)
	../../../go/pkg/mod/github.com/matrixorigin/linter@v0.0.0-20241101034[9](https://github.com/matrixorigin/matrixone/actions/runs/11626869179/job/32379327084?pr=19718#step:6:10)05-36c04639c58c/checklog/checklog.go:58 +0x131
golang.org/x/tools/go/analysis/unitchecker.run.func5.1()
	../../../go/pkg/mod/golang.org/x/tools@v0.7.1-0.20230308011436-dd1e2f66b242/go/analysis/unitchecker/unitchecker.go:359 +0x89e
sync.(*Once).doSlow(0x6e23a0?, 0xc0006bff20?)
	/opt/hostedtoolcache/go/1.23.0/x64/src/sync/once.go:76 +0xb4
sync.(*Once).Do(...)
	/opt/hostedtoolcache/go/1.23.0/x64/src/sync/once.go:67
golang.org/x/tools/go/analysis/unitchecker.run.func5(0x95dee0)
	../../../go/pkg/mod/golang.org/x/tools@v0.7.1-0.20230308011436-dd1e2f66b242/go/analysis/unitchecker/unitchecker.go:3[10](https://github.com/matrixorigin/matrixone/actions/runs/11626869179/job/32379327084?pr=19718#step:6:11) +0x19e
golang.org/x/tools/go/analysis/unitchecker.run.func6.1(0x0?)
	../../../go/pkg/mod/golang.org/x/tools@v0.7.1-0.20230308011436-dd1e2f66b242/go/analysis/unitchecker/unitchecker.go:371 +0x23
created by golang.org/x/tools/go/analysis/unitchecker.run.func6 in goroutine 1
	../../../go/pkg/mod/golang.org/x/tools@v0.7.1-0.202303080[11](https://github.com/matrixorigin/matrixone/actions/runs/11626869179/job/32379327084?pr=19718#step:6:12)436-dd1e2f66b242/go/analysis/unitchecker/unitchecker.go:370 +0x47
make: *** [Makefile:244: static-check] Error 1
```

**Comment by xzxiong** [comment]
fixed, @daviszhen  pta;

**Comment by daviszhen** [comment]
fixed
